### ISSUE TITLE
Pas d'ENT mais identifiant et mot de passe

### ISSUE THREAD

**Issue by Lunyyx** [Androz2091/pronote-bot#1]
Bonjour,
Je voulais savoir s'il est possible de se connecter à ce bot sans ENT ?
Merci d'avance

**Comment by Androz2091** [comment]
Bonjour,
En soit tu peux tout à fait réutiliser le code de ce repo pour parser les données de pronote, mais il te faudra quand même adapter certaines parties du code notamment les fichiers `pronote/genConnectedPage.js` et `pronote/fetchStudent.js`. Ces deux fichiers vont sur l'ent, remplissent le formulaire de connexion puis utilisent les cookies pour accéder à pronote. Dans ton cas, il faudra que tu fasses en sorte que le bot ailles directement sur pronote puis remplisse le formulaire de connexion de pronote. Après ça devrait être bon pour le reste !

**Comment by Lunyyx** [comment]
Bonjour, 
Excusez-moi de ma réponse tardive
Comment puis-je justement faire en sorte que le bot se connecte grâce a mes identifiants (Et dont pas d'ent) ? Que dois-je modifier dans les fichiers ?
Merci d'avance pour votre réponse
