### ISSUE TITLE
Erreur de login

### ISSUE THREAD

**Issue by Superalexandre** [Androz2091/pronote-bot#3]
(node:27656) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at Function.from (buffer.js:313:9)
    at AccountRepository.encryptPassword (/home/Sudref/node_modules/instagram-private-api/dist/repositories/account.repository.js:61:25)
    at AccountRepository.login (/home/Sudref/node_modules/instagram-private-api/dist/repositories/account.repository.js:12:42)
    at loginToInstagram (/home/Sudref/instragram/init.js:68:33)
    at /home/Sudref/instragram/init.js:24:26
(node:27656) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:27656) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Androz2091** [comment]
Bonjour,
Essayez de downgrade la version d'instagram-private-api :
`npm install instagram-private-api@1.37`. Si le problème persiste, contactez les via leur Github.
