### ISSUE TITLE
Ne réponds pas

### ISSUE THREAD

**Issue by Mr-KayJayDee** [Androz2091/pronote-bot#4]
Le message est vu par le bot, je ne sais pas si mes lien de pronotes sont bon.

```cmd
(node:3244) UnhandledPromiseRejectionWarning: TypeError: require(...).find is not a function
    at InstaUser.get logged [as logged] (C:\Users\minit\Desktop\pronote-bot\pronote-bot\instagram\InstaUser.js:35:44)
    at RealtimeClient.<anonymous> (C:\Users\minit\Desktop\pronote-bot\pronote-bot\pronote-bot.js:135:36)
(node:3244) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

Voici ma config :

```json
{
    "username": "hidden",
    "password": "hidden",

    "entLoginURL": "https://teleservices.ac-poitiers.fr/login/ct_logon_vk.jsp?CT_ORIG_URL=%2Fdispatcher%2F&ct_orig_uri=http%3A%2F%2Fteleservices.ac-poitiers.fr%2Fdispatcher%2F",
    "entHomePageURL": "https://mon.lyceeconnecte.fr/timeline/timeline",
    "entMenuURL": "http://ent.ac-poitiers.fr/",
    "pronoteURL": "https://www.index-education.com/",

    "fullLog": true,

    "modeVacances": false,

    "coronaMode": true

}
```

**Comment by Androz2091** [comment]
Bonjour @Mr-KayJayDee
Le système d'authentification est très spécifique, il faut l'adapter si vous souhaitez utiliser le code.

Si vous utilisez la v2, le fichier a modifier sera celui-là : https://github.com/Androz2091/pronote-bot/blob/v2/pronote/Student.js

Et si vous utilisez la v1, les fichiers dans ce dossier : 
https://github.com/Androz2091/pronote-bot/tree/master/pronote

Notez que ça peut être difficile si vous ne connaissez pas bien Puppeteer...

**Comment by Mr-KayJayDee** [comment]
> Bonjour @Mr-KayJayDee
> Le système d'authentification est très spécifique, il faut l'adapter si vous souhaitez utiliser le code.
> 
> Si vous utilisez la v2, le fichier a modifier sera celui-là : https://github.com/Androz2091/pronote-bot/blob/v2/pronote/Student.js
> 
> Et si vous utilisez la v1, les fichiers dans ce dossier : 
> https://github.com/Androz2091/pronote-bot/tree/master/pronote
> 
> Notez que ça peut être difficile si vous ne connaissez pas bien Puppeteer...

D'accord merci
